version: '3.8'

services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:5173"
    volumes:
      - ./frontend:/app
      - node_modules:/app/node_modules # If node module is not installed in the container properly

  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - redis
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/app

  redis:
    container_name: redis
    image: "redis:7.4.2-alpine"
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data # Persist Redis data

networks:
  default:
    driver: bridge

volumes:
  redis-data:
  node_modules: